services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app/app
    expose:
      - 8000
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - app_network

networks:
  app_network:
    driver: bridge